import {
  User,
  Department,
  Folder,
  DocumentItem,
  Device,
  AuditLog,
  ApiKey,
  WebhookConfig,
  SystemNotification,
  PermissionType,
} from '../types';

export const INITIAL_DEPARTMENTS: Department[] = [
  {
    id: 'dept-financeiro',
    name: 'Financeiro',
    code: 'FIN',
    iconName: 'DollarSign',
    color: '#3b82f6',
    storageLimitBytes: 500 * 1024 * 1024 * 1024, // 500 GB
    storageUsedBytes: 327 * 1024 * 1024 * 1024, // 327 GB
    managerId: 'user-gestor-fin',
    managerName: 'Marcos Silva',
    description: 'Gestão contábil, fiscal, contas a pagar/receber e orçamentos.',
    isLocked: true,
    itemCount: 12,
  },
  {
    id: 'dept-rh',
    name: 'RH',
    code: 'RH',
    iconName: 'Users',
    color: '#8b5cf6',
    storageLimitBytes: 200 * 1024 * 1024 * 1024, // 200 GB
    storageUsedBytes: 184 * 1024 * 1024 * 1024, // 184 GB
    managerId: 'user-gestor-rh',
    managerName: 'Juliana Prado',
    description: 'Recursos Humanos, admissões, folha de pagamento e benefícios.',
    isLocked: true,
    itemCount: 8,
  },
  {
    id: 'dept-comercial',
    name: 'Comercial',
    code: 'COM',
    iconName: 'Briefcase',
    color: '#10b981',
    storageLimitBytes: 350 * 1024 * 1024 * 1024, // 350 GB
    storageUsedBytes: 142 * 1024 * 1024 * 1024, // 142 GB
    managerId: 'user-gestor-com',
    managerName: 'Eduardo Castro',
    description: 'Contratos comerciais, propostas, clientes e pipeline de vendas.',
    isLocked: true,
    itemCount: 15,
  },
  {
    id: 'dept-ti',
    name: 'TI',
    code: 'TI',
    iconName: 'Server',
    color: '#06b6d4',
    storageLimitBytes: 300 * 1024 * 1024 * 1024, // 300 GB
    storageUsedBytes: 85 * 1024 * 1024 * 1024, // 85 GB
    managerId: 'user-gestor-ti',
    managerName: 'Luciano Mendes',
    description: 'Infraestrutura, políticas de segurança, inventário e auditorias de TI.',
    isLocked: true,
    itemCount: 10,
  },
  {
    id: 'dept-marketing',
    name: 'Marketing',
    code: 'MKT',
    iconName: 'Megaphone',
    color: '#ec4899',
    storageLimitBytes: 250 * 1024 * 1024 * 1024, // 250 GB
    storageUsedBytes: 98 * 1024 * 1024 * 1024, // 98 GB
    managerId: 'user-gestor-mkt',
    managerName: 'Camila Rocha',
    description: 'Campanhas, ativos de marca, peças publicitárias e relatórios de mídia.',
    isLocked: true,
    itemCount: 6,
  },
  {
    id: 'dept-projetos',
    name: 'Projetos',
    code: 'PRJ',
    iconName: 'FolderKanban',
    color: '#f59e0b',
    storageLimitBytes: 400 * 1024 * 1024 * 1024, // 400 GB
    storageUsedBytes: 210 * 1024 * 1024 * 1024, // 210 GB
    managerId: 'user-gestor-prj',
    managerName: 'Gustavo Paiva',
    description: 'Documentação de arquitetura de software, especificações técnicas e cronogramas.',
    isLocked: true,
    itemCount: 9,
  },
  {
    id: 'dept-gerais',
    name: 'Documentos Gerais',
    code: 'GER',
    iconName: 'Files',
    color: '#64748b',
    storageLimitBytes: 150 * 1024 * 1024 * 1024, // 150 GB
    storageUsedBytes: 45 * 1024 * 1024 * 1024, // 45 GB
    managerId: 'user-diretor',
    managerName: 'Roberto Mendes',
    description: 'Políticas corporativas, manuais de conduta e comunicados institucionais.',
    isLocked: false,
    itemCount: 14,
  },
  {
    id: 'dept-arquivados',
    name: 'Arquivados',
    code: 'ARQ',
    iconName: 'Archive',
    color: '#475569',
    storageLimitBytes: 1024 * 1024 * 1024 * 1024, // 1 TB
    storageUsedBytes: 310 * 1024 * 1024 * 1024, // 310 GB
    managerId: 'user-diretor',
    managerName: 'Roberto Mendes',
    description: 'Registros fiscais e contábeis de anos anteriores com retenção legal obrigatória.',
    isLocked: true,
    itemCount: 5,
  },
];

export const INITIAL_FOLDERS: Folder[] = [
  // Financeiro Subfolders
  {
    id: 'folder-fin-relatorios',
    name: 'Relatórios',
    departmentId: 'dept-financeiro',
    departmentName: 'Financeiro',
    parentId: null,
    createdAt: '2025-01-10T08:00:00Z',
    updatedAt: '07/10/2025 10:30',
    isLocked: false,
    itemCount: 3,
    description: 'DREs consolidados, balancetes mensais e relatórios gerenciais.',
  },
  {
    id: 'folder-fin-pagar',
    name: 'Contas a Pagar',
    departmentId: 'dept-financeiro',
    departmentName: 'Financeiro',
    parentId: null,
    createdAt: '2025-01-10T08:00:00Z',
    updatedAt: '06/10/2025 16:45',
    isLocked: false,
    itemCount: 8,
    description: 'Comprovantes de pagamento, duplicatas e boletos de fornecedores.',
  },
  {
    id: 'folder-fin-receber',
    name: 'Contas a Receber',
    departmentId: 'dept-financeiro',
    departmentName: 'Financeiro',
    parentId: null,
    createdAt: '2025-01-10T08:00:00Z',
    updatedAt: '05/10/2025 14:15',
    isLocked: false,
    itemCount: 5,
    description: 'Faturamentos, notas fiscais emitidas e relatórios de inadimplência.',
  },
  {
    id: 'folder-fin-bancos',
    name: 'Bancos',
    departmentId: 'dept-financeiro',
    departmentName: 'Financeiro',
    parentId: null,
    createdAt: '2025-01-10T08:00:00Z',
    updatedAt: '04/10/2025 11:20',
    isLocked: true,
    itemCount: 4,
    description: 'Extratos bancários consolidados e conciliações financeiras confidenciais.',
  },
  {
    id: 'folder-fin-fiscal',
    name: 'Fiscal',
    departmentId: 'dept-financeiro',
    departmentName: 'Financeiro',
    parentId: null,
    createdAt: '2025-01-10T08:00:00Z',
    updatedAt: '03/10/2025 09:10',
    isLocked: true,
    itemCount: 6,
    description: 'Apuração de impostos federais, estaduais e municipais.',
  },

  // RH Subfolders
  {
    id: 'folder-rh-pessoais',
    name: 'Documentos Pessoais',
    departmentId: 'dept-rh',
    departmentName: 'RH',
    parentId: null,
    createdAt: '2025-02-01T08:00:00Z',
    updatedAt: '12/09/2025 15:20',
    isLocked: true,
    itemCount: 4,
    description: 'Documentos confidenciais dos funcionários (RG, CPF, Comprovantes).',
  },
  {
    id: 'folder-rh-contratos',
    name: 'Contratos',
    departmentId: 'dept-rh',
    departmentName: 'RH',
    parentId: null,
    createdAt: '2025-02-01T08:00:00Z',
    updatedAt: '10/09/2025 11:30',
    isLocked: true,
    itemCount: 6,
    description: 'Contratos de trabalho CLT, PJ, termos de confidencialidade e aditivos.',
  },
  {
    id: 'folder-rh-beneficios',
    name: 'Benefícios',
    departmentId: 'dept-rh',
    departmentName: 'RH',
    parentId: null,
    createdAt: '2025-02-01T08:00:00Z',
    updatedAt: '08/09/2025 14:00',
    isLocked: false,
    itemCount: 3,
    description: 'Planos de saúde, odontológicos, vale-alimentação e transporte.',
  },
  {
    id: 'folder-rh-folha',
    name: 'Folha de Pagamento',
    departmentId: 'dept-rh',
    departmentName: 'RH',
    parentId: null,
    createdAt: '2025-02-01T08:00:00Z',
    updatedAt: '05/09/2025 10:00',
    isLocked: true,
    itemCount: 7,
    description: 'Holerites mensais, guias de FGTS e INSS.',
  },

  // Comercial Subfolders
  {
    id: 'folder-com-propostas',
    name: 'Propostas Comerciais',
    departmentId: 'dept-comercial',
    departmentName: 'Comercial',
    parentId: null,
    createdAt: '2025-03-01T08:00:00Z',
    updatedAt: '06/10/2025 17:30',
    isLocked: false,
    itemCount: 8,
  },
  {
    id: 'folder-com-clientes',
    name: 'Contratos de Clientes',
    departmentId: 'dept-comercial',
    departmentName: 'Comercial',
    parentId: null,
    createdAt: '2025-03-01T08:00:00Z',
    updatedAt: '04/10/2025 16:10',
    isLocked: true,
    itemCount: 7,
  },

  // TI Subfolders
  {
    id: 'folder-ti-seguranca',
    name: 'Políticas de Segurança',
    departmentId: 'dept-ti',
    departmentName: 'TI',
    parentId: null,
    createdAt: '2025-01-15T08:00:00Z',
    updatedAt: '01/10/2025 09:00',
    isLocked: false,
    itemCount: 5,
  },
];

export const INITIAL_DOCUMENTS: DocumentItem[] = [
  // Financeiro Documents
  {
    id: 'doc-relatorio-financeiro',
    name: 'Relatório Financeiro.pdf',
    extension: 'pdf',
    mimeType: 'application/pdf',
    sizeBytes: 1.2 * 1024 * 1024, // 1.2 MB
    folderId: 'folder-fin-relatorios',
    departmentId: 'dept-financeiro',
    departmentName: 'Financeiro',
    ownerId: 'user-mariana',
    ownerName: 'Mariana Costa',
    createdAt: '2025-10-06T10:00:00Z',
    updatedAt: '06/10/2025',
    hashSha256: '9f86d081884c7d659a2feaa0c55ad015a3bf4f1b2b0b822cd15d6c15b0f00a08',
    currentVersion: 3,
    versions: [
      {
        id: 'ver-1',
        documentId: 'doc-relatorio-financeiro',
        versionNumber: 1,
        versionLabel: 'v1.0 (Rascunho Inicial)',
        createdAt: '01/10/2025 14:20',
        createdBy: 'Mariana Costa',
        sizeBytes: 1.0 * 1024 * 1024,
        hashSha256: 'a1b2c3d4e5f67890123456789abcdef0123456789abcdef0123456789abcdef0',
        changeLog: 'Criação inicial dos demonstrativos financeiros de setembro.',
      },
      {
        id: 'ver-2',
        documentId: 'doc-relatorio-financeiro',
        versionNumber: 2,
        versionLabel: 'v2.0 (Ajuste Tributário)',
        createdAt: '04/10/2025 09:15',
        createdBy: 'Marcos Silva',
        sizeBytes: 1.1 * 1024 * 1024,
        hashSha256: 'b2c3d4e5f6a17890123456789abcdef0123456789abcdef0123456789abcdef0',
        changeLog: 'Inclusão das deduções de PIS/COFINS e conciliação bancária.',
      },
      {
        id: 'ver-3',
        documentId: 'doc-relatorio-financeiro',
        versionNumber: 3,
        versionLabel: 'v3.0 (Versão Oficial Aprovada)',
        createdAt: '06/10/2025 10:00',
        createdBy: 'Marcos Silva',
        sizeBytes: 1.2 * 1024 * 1024,
        hashSha256: '9f86d081884c7d659a2feaa0c55ad015a3bf4f1b2b0b822cd15d6c15b0f00a08',
        changeLog: 'Assinatura digital e homologação final pela Diretoria.',
      },
    ],
    isFavorite: true,
    isArchived: false,
    isShared: true,
    contentSummary: 'Demonstrativo completo de Receitas x Despesas de Setembro 2025 com Saldo de R$ 145.690,00.',
    status: 'active',
    scanStatus: 'clean',
    tags: ['Oficial', 'Setembro 2025', 'DRE'],
  },
  {
    id: 'doc-fluxo-caixa',
    name: 'Fluxo de Caixa.xlsx',
    extension: 'xlsx',
    mimeType: 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
    sizeBytes: 245 * 1024, // 245 KB
    folderId: 'folder-fin-relatorios',
    departmentId: 'dept-financeiro',
    departmentName: 'Financeiro',
    ownerId: 'user-mariana',
    ownerName: 'Mariana Costa',
    createdAt: '2025-10-07T08:30:00Z',
    updatedAt: '07/10/2025',
    hashSha256: 'e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855',
    currentVersion: 2,
    versions: [
      {
        id: 'ver-fc-1',
        documentId: 'doc-fluxo-caixa',
        versionNumber: 1,
        versionLabel: 'v1.0',
        createdAt: '02/10/2025',
        createdBy: 'Mariana Costa',
        sizeBytes: 210 * 1024,
        hashSha256: 'c3d4e5f6a1b27890123456789abcdef0123456789abcdef0123456789abcdef0',
        changeLog: 'Projeção semanal preliminar.',
      },
      {
        id: 'ver-fc-2',
        documentId: 'doc-fluxo-caixa',
        versionNumber: 2,
        versionLabel: 'v2.0 (Atualizado)',
        createdAt: '07/10/2025',
        createdBy: 'Mariana Costa',
        sizeBytes: 245 * 1024,
        hashSha256: 'e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855',
        changeLog: 'Consolidação de entradas da primeira semana de outubro.',
      },
    ],
    isFavorite: true,
    isArchived: false,
    isShared: false,
    status: 'active',
    scanStatus: 'clean',
  },
  {
    id: 'doc-planejamento-orcamentario',
    name: 'Planejamento Orçamentário.docx',
    extension: 'docx',
    mimeType: 'application/vnd.openxmlformats-officedocument.wordprocessingml.document',
    sizeBytes: 320 * 1024, // 320 KB
    folderId: 'folder-fin-relatorios',
    departmentId: 'dept-financeiro',
    departmentName: 'Financeiro',
    ownerId: 'user-gestor-fin',
    ownerName: 'Marcos Silva',
    createdAt: '2025-10-05T11:00:00Z',
    updatedAt: '05/10/2025',
    hashSha256: '5e884898da28047151d0e56f8dc6292773603d0d6aabbdd62a11ef721d1542d8',
    currentVersion: 1,
    versions: [
      {
        id: 'ver-po-1',
        documentId: 'doc-planejamento-orcamentario',
        versionNumber: 1,
        versionLabel: 'v1.0 (Oficial)',
        createdAt: '05/10/2025',
        createdBy: 'Marcos Silva',
        sizeBytes: 320 * 1024,
        hashSha256: '5e884898da28047151d0e56f8dc6292773603d0d6aabbdd62a11ef721d1542d8',
        changeLog: 'Diretrizes orçamentárias corporativas para o ano de 2026.',
      },
    ],
    isFavorite: false,
    isArchived: false,
    isShared: true,
    status: 'active',
    scanStatus: 'clean',
  },

  // RH Documents
  {
    id: 'doc-lista-funcionarios',
    name: 'Lista de Funcionários.xlsx',
    extension: 'xlsx',
    mimeType: 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
    sizeBytes: 180 * 1024, // 180 KB
    folderId: 'folder-rh-pessoais',
    departmentId: 'dept-rh',
    departmentName: 'RH',
    ownerId: 'user-gestor-rh',
    ownerName: 'Juliana Prado',
    createdAt: '2025-09-05T09:00:00Z',
    updatedAt: '05/09/2025',
    hashSha256: '4b227777d4dd1fc61c6f884f48641d02b4d121d3fd328cb08b5531fcacdabf8a',
    currentVersion: 1,
    versions: [],
    isFavorite: false,
    isArchived: false,
    isShared: false,
    status: 'active',
    scanStatus: 'clean',
  },
  {
    id: 'doc-regulamento-interno',
    name: 'Regulamento Interno.pdf',
    extension: 'pdf',
    mimeType: 'application/pdf',
    sizeBytes: 840 * 1024, // 840 KB
    folderId: 'folder-rh-pessoais',
    departmentId: 'dept-rh',
    departmentName: 'RH',
    ownerId: 'user-gestor-rh',
    ownerName: 'Juliana Prado',
    createdAt: '2025-09-02T14:30:00Z',
    updatedAt: '02/09/2025',
    hashSha256: 'ef2d127de37b942baad06145e54b0c619a1f22327b2ebbcfbec78f5564afe39d',
    currentVersion: 2,
    versions: [],
    isFavorite: true,
    isArchived: false,
    isShared: true,
    status: 'active',
    scanStatus: 'clean',
  },

  // Comercial Documents
  {
    id: 'doc-proposta-2025',
    name: 'Proposta Comercial - Enterprise 2025.pdf',
    extension: 'pdf',
    mimeType: 'application/pdf',
    sizeBytes: 2.1 * 1024 * 1024,
    folderId: 'folder-com-propostas',
    departmentId: 'dept-comercial',
    departmentName: 'Comercial',
    ownerId: 'user-ana',
    ownerName: 'Ana Oliveira',
    createdAt: '2025-10-06T11:20:00Z',
    updatedAt: '06/10/2025',
    hashSha256: '7d793037a0760186574b0282f2f435e7b1e73777d79e5cad1add2fbac372ee36',
    currentVersion: 1,
    versions: [],
    isFavorite: true,
    isArchived: false,
    isShared: true,
    status: 'active',
    scanStatus: 'clean',
  },

  // TI Documents
  {
    id: 'doc-politica-iso27001',
    name: 'Política de Segurança da Informação (ISO 27001).pdf',
    extension: 'pdf',
    mimeType: 'application/pdf',
    sizeBytes: 1.8 * 1024 * 1024,
    folderId: 'folder-ti-seguranca',
    departmentId: 'dept-ti',
    departmentName: 'TI',
    ownerId: 'user-rafael',
    ownerName: 'Rafael Souza',
    createdAt: '2025-10-01T08:00:00Z',
    updatedAt: '01/10/2025',
    hashSha256: '2c26b46b68ffc68ff99b453c1d30413413422d706483bfa0f98a5e886266e7ae',
    currentVersion: 4,
    versions: [],
    isFavorite: false,
    isArchived: false,
    isShared: true,
    status: 'active',
    scanStatus: 'clean',
  },
];

export const ALL_PERMISSIONS: PermissionType[] = [
  'VIEW_FOLDER',
  'LIST_FILES',
  'VIEW_DOCUMENT',
  'DOWNLOAD_DOCUMENT',
  'UPLOAD_DOCUMENT',
  'EDIT_DOCUMENT',
  'DELETE_DOCUMENT',
  'CREATE_FOLDER',
  'DELETE_FOLDER',
  'MOVE_DOCUMENT',
  'RENAME_DOCUMENT',
  'SHARE_DOCUMENT',
  'MANAGE_PERMISSIONS',
  'MANAGE_USERS',
  'MANAGE_DEVICES',
  'VIEW_AUDIT',
];

export const INITIAL_USERS: User[] = [
  {
    id: 'user-marcos-dev',
    name: 'Marcos Monteiro',
    email: 'marcosmonteiro.devs@gmail.com',
    matricula: 'DEV-001',
    cpf: '000.000.000-00',
    phone: '+55 11 98888-7777',
    role: 'DEVELOPER',
    departmentId: 'dept-ti',
    departmentName: 'TI / Engenharia',
    cargo: 'Desenvolvedor / Administrador do Sistema',
    avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&q=80&w=256',
    status: 'ACTIVE',
    failedLoginAttempts: 0,
    twoFactorEnabled: true,
    twoFactorSecret: 'JBSWY3DPEHPK3PXP',
    createdAt: '2024-01-01T00:00:00Z',
    lastLoginAt: 'Hoje às 10:45',
    permittedFolderIds: ['*'], // Full access across all folders
    granularPermissions: {
      '*': ALL_PERMISSIONS,
    },
  },
];

export const INITIAL_AUDIT_LOGS: AuditLog[] = [
  {
    id: 'audit-001',
    timestamp: '07/10/2025 10:42',
    userId: 'user-mariana',
    userName: 'Mariana Costa',
    role: 'EMPLOYEE',
    department: 'Financeiro',
    action: 'LOGIN',
    resourceName: 'Sessão Web Segura',
    details: 'Login autenticado via 2FA TOTP com sucesso.',
    ipAddress: '187.54.120.45',
    deviceInfo: 'Chrome 129 / macOS Sonoma',
    result: 'SUCCESS',
    hash: 'a9f76b912c9b3d1e',
  },
  {
    id: 'audit-002',
    timestamp: '07/10/2025 10:37',
    userId: 'user-joao',
    userName: 'João Alves',
    role: 'EMPLOYEE',
    department: 'RH',
    action: 'DOCUMENT_VIEWED',
    resourceName: 'Benefícios 2025.pdf',
    details: 'Visualização autorizada do documento no leitor seguro.',
    ipAddress: '201.86.42.11',
    deviceInfo: 'Edge 128 / Windows 11',
    result: 'SUCCESS',
    hash: 'b8e65a801b8a2c0d',
  },
  {
    id: 'audit-003',
    timestamp: '07/10/2025 10:25',
    userId: 'user-fernanda',
    userName: 'Fernanda Lima',
    role: 'EMPLOYEE',
    department: 'Comercial',
    action: 'LOGIN',
    resourceName: 'Sessão Web Segura',
    details: 'Autenticação de dispositivo confiável realizada.',
    ipAddress: '177.132.88.94',
    deviceInfo: 'Safari / iOS 18.0',
    result: 'SUCCESS',
    hash: 'c7d5497f0a791b9c',
  },
  {
    id: 'audit-004',
    timestamp: '07/10/2025 09:58',
    userId: 'user-rafael',
    userName: 'Rafael Souza',
    role: 'EMPLOYEE',
    department: 'TI',
    action: 'PERMISSIONS_MODIFIED',
    resourceName: 'Políticas de Segurança',
    details: 'Alteração de permissões granulares de leitura para o grupo TI-Suporte.',
    ipAddress: '189.100.22.4',
    deviceInfo: 'Firefox 130 / Ubuntu 24.04',
    result: 'SUCCESS',
    hash: 'd6c4386e99680a8b',
  },
  {
    id: 'audit-005',
    timestamp: '07/10/2025 09:12',
    userId: 'user-diretor',
    userName: 'Roberto Mendes',
    role: 'DIRECTOR',
    department: 'Diretoria Executiva',
    action: 'DOCUMENT_DOWNLOADED',
    resourceName: 'Relatório Financeiro.pdf (v3.0)',
    details: 'Download seguro criptografado com marca d’água digital efetuado.',
    ipAddress: '187.32.99.12',
    deviceInfo: 'Chrome 129 / macOS Sequoia',
    result: 'SUCCESS',
    hash: 'e5b3275d8857997a',
  },
  {
    id: 'audit-006',
    timestamp: '07/10/2025 08:45',
    userId: 'user-carlos-dev',
    userName: 'Carlos Silva',
    role: 'DEVELOPER',
    department: 'TI / Engenharia',
    action: 'DEVICE_APPROVED',
    resourceName: 'Notebook Dell XPS (Mariana Costa)',
    details: 'Aprovação manual de novo dispositivo confiável pelo administrador.',
    ipAddress: '179.180.200.15',
    deviceInfo: 'Chrome 129 / Linux Dev Workstation',
    result: 'SUCCESS',
    hash: 'f4a2164c77468869',
  },
  {
    id: 'audit-007',
    timestamp: '07/10/2025 08:10',
    userId: 'unknown',
    userName: 'tentativa_desconhecida@externo.com',
    role: 'EMPLOYEE',
    department: 'Externo',
    action: 'LOGIN_BLOCKED',
    resourceName: 'Tentativa de Acesso Não Autorizada',
    details: '2 tentativas de senha incorretas detectadas. IP bloqueado temporariamente.',
    ipAddress: '45.143.200.8',
    deviceInfo: 'Python-Requests / Unknown OS',
    result: 'BLOCKED',
    hash: '1391053b66357758',
  },
];

export const INITIAL_DEVICES: Device[] = [
  {
    id: 'dev-001',
    userId: 'user-carlos-dev',
    userName: 'Carlos Silva',
    deviceName: 'Workstation Linux (Dev Arch)',
    deviceType: 'desktop',
    os: 'Linux x86_64',
    browser: 'Chrome 129',
    ipAddress: '179.180.200.15',
    lastAccessAt: 'Hoje às 10:45',
    status: 'TRUSTED',
    fingerprintHash: 'sha256-a9f87c6b54321',
    registeredAt: '2024-01-10',
    isCurrent: true,
  },
  {
    id: 'dev-002',
    userId: 'user-carlos-dev',
    userName: 'Carlos Silva',
    deviceName: 'iPhone 15 Pro (Móvel Corporativo)',
    deviceType: 'mobile',
    os: 'iOS 18.0',
    browser: 'Mobile Safari',
    ipAddress: '187.54.120.45',
    lastAccessAt: 'Ontem às 22:15',
    status: 'TRUSTED',
    fingerprintHash: 'sha256-b8e76a5432109',
    registeredAt: '2024-02-15',
  },
  {
    id: 'dev-003',
    userId: 'user-ana',
    userName: 'Ana Oliveira',
    deviceName: 'MacBook Air M2',
    deviceType: 'desktop',
    os: 'macOS Sonoma',
    browser: 'Chrome 129',
    ipAddress: '177.132.88.94',
    lastAccessAt: 'Hoje às 10:15',
    status: 'TRUSTED',
    fingerprintHash: 'sha256-c7d65b4321098',
    registeredAt: '2024-05-10',
    isCurrent: false,
  },
  {
    id: 'dev-004',
    userId: 'user-mariana',
    userName: 'Mariana Costa',
    deviceName: 'Notebook Dell XPS 15',
    deviceType: 'desktop',
    os: 'Windows 11 Enterprise',
    browser: 'Edge 128',
    ipAddress: '187.54.120.45',
    lastAccessAt: 'Hoje às 10:42',
    status: 'TRUSTED',
    fingerprintHash: 'sha256-d6c54a3210987',
    registeredAt: '2024-06-01',
  },
  {
    id: 'dev-005',
    userId: 'user-joao',
    userName: 'João Alves',
    deviceName: 'Tablet Samsung Galaxy S9 (Novo)',
    deviceType: 'tablet',
    os: 'Android 14',
    browser: 'Chrome Mobile',
    ipAddress: '201.86.42.11',
    lastAccessAt: 'Hoje às 07:30',
    status: 'PENDING_APPROVAL',
    fingerprintHash: 'sha256-e5b43a2109876',
    registeredAt: 'Hoje às 07:30',
  },
  {
    id: 'dev-006',
    userId: 'user-rafael',
    userName: 'Rafael Souza',
    deviceName: 'Dispositivo Desconhecido (Rússia/Proxy)',
    deviceType: 'desktop',
    os: 'Windows 10',
    browser: 'Tor Browser',
    ipAddress: '45.143.200.8',
    lastAccessAt: 'Ontem às 03:15',
    status: 'BLOCKED',
    fingerprintHash: 'sha256-f4a32a1098765',
    registeredAt: 'Ontem às 03:15',
  },
];

export const INITIAL_API_KEYS: ApiKey[] = [
  {
    id: 'key-001',
    name: 'Integração ERP SAP Finanças',
    keyPreview: 'dcs_live_••••••••98a2',
    keyHash: 'hash_839218391283918239',
    scopes: ['read:documents', 'write:documents', 'read:storage'],
    createdAt: '2024-04-10',
    lastUsedAt: 'Hoje às 10:30',
    status: 'ACTIVE',
    createdBy: 'Carlos Silva (DEV)',
  },
  {
    id: 'key-002',
    name: 'Pipeline CI/CD Backup Noturno',
    keyPreview: 'dcs_live_••••••••41ef',
    keyHash: 'hash_994827184719284712',
    scopes: ['read:documents', 'export:audit'],
    createdAt: '2024-06-15',
    lastUsedAt: 'Ontem às 23:59',
    status: 'ACTIVE',
    createdBy: 'Carlos Silva (DEV)',
  },
];

export const INITIAL_WEBHOOKS: WebhookConfig[] = [
  {
    id: 'wh-001',
    name: 'Alerta SOC & SIEM Corporativo',
    url: 'https://siem.empresa.com/api/v1/docsecure-events',
    events: ['device.blocked', 'user.blocked', 'audit.created', 'storage.limit_reached'],
    secretKey: 'whsec_••••••••••••••••3a9b',
    status: 'ACTIVE',
    lastTriggeredAt: 'Hoje às 08:10',
    successRate: 99.8,
  },
  {
    id: 'wh-002',
    name: 'Notificação Slack Contratos Financeiros',
    url: 'https://hooks.slack.com/services/T00/B00/XXXX',
    events: ['document.uploaded', 'permission.changed'],
    secretKey: 'whsec_••••••••••••••••7c4d',
    status: 'ACTIVE',
    lastTriggeredAt: 'Ontem às 16:45',
    successRate: 100,
  },
];

export const INITIAL_NOTIFICATIONS: SystemNotification[] = [
  {
    id: 'notif-1',
    title: 'Novo Dispositivo Pendente',
    message: 'João Alves solicitou aprovação para o dispositivo Samsung Galaxy Tab S9.',
    type: 'security',
    createdAt: 'Hoje às 07:30',
    read: false,
  },
  {
    id: 'notif-2',
    title: 'Documento Compartilhado',
    message: 'Mariana Costa compartilhou "Relatório Financeiro.pdf" com o setor.',
    type: 'info',
    createdAt: 'Hoje às 10:00',
    read: false,
  },
  {
    id: 'notif-3',
    title: 'Armazenamento do RH em 92%',
    message: 'O setor de RH atingiu 184 GB dos 200 GB contratados. Considere expandir a quota.',
    type: 'warning',
    createdAt: '06/10/2025',
    read: true,
  },
];
